# Generated by Django 5.2.3 on 2025-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, help_text="Например: 'fa-home' для FontAwesome", max_length=50),
        ),
    ]
